# Name of the Namespace to use
namespace: mongodb

# OpenShift manages security context on its own
managedSecurityContext: true

operator:
  # Execution environment for the operator, dev or prod. Use dev for more verbose logging
  env: prod

  # Name that will be assigned to most of internal Kubernetes objects like ServiceAccount, Role etc.
  name: mongodb-enterprise-operator

  # Name of the operator image
  operator_image_name: enterprise-operator

  # Name of the deployment of the operator pod
  deployment_name: mongodb-enterprise-operator

  # Version of mongodb-enterprise-operator
  version: 1.13.0

  # The Custom Resources that will be watched by the Operator. Needs to be changed if only some of the CRDs are installed
  watchedResources:
  - mongodb
  - opsmanagers
  - mongodbusers

  nodeSelector: {}

  tolerations: []

  affinity: {}

## Database
database:
  name: enterprise-database
  version: 2.0.2

initDatabase:
  name: mongodb-enterprise-init-database
  version: 1.0.5

## Ops Manager
opsManager:
  name: mongodb-enterprise-ops-manager

initOpsManager:
  name: mongodb-enterprise-init-ops-manager
  version: 1.0.5

initAppDb:
  name: mongodb-enterprise-init-appdb
  version: 1.0.8

agent:
  name: mongodb-agent
  version: 11.0.5.6963-1

mongodb:
  name: mongodb-enterprise-appdb-database
  repo: quay.io/mongodb


## Registry
registry:
  # The pull secret must be specified
  imagePullSecrets:
  pullPolicy: Always
  database: registry.connect.redhat.com/mongodb
  operator: registry.connect.redhat.com/mongodb
  initDatabase: registry.connect.redhat.com/mongodb
  initOpsManager: registry.connect.redhat.com/mongodb
  opsManager: registry.connect.redhat.com/mongodb
  initAppDb: registry.connect.redhat.com/mongodb
  appDb: registry.connect.redhat.com/mongodb
  agent: registry.connect.redhat.com/mongodb


# Set this to false to disable subresource utilization
# It might be required on some versions of Openshift
subresourceEnabled: true
