# Create the CustomerResourceDefinition for MongoDB custom types.
createCrds: true

# Name of the Namespace to use
namespace: mongodb

# Set this to true if your cluster is managing SecurityContext for you.
# If running OpenShift (Cloud, Minishift, etc.), set this to true.
managedSecurityContext: false

operator:
  # Execution environment for the operator, dev or prod. Use dev for more verbose logging
  env: prod

  # Name that will be assigned to most of internal Kubernetes objects like Deployment, ServiceAccount, Role etc.
  name: mongodb-enterprise-operator

  # Version of mongodb-enterprise-operator and mongodb-enterprise-database images
  version: 0.6

registry:
  # Specify if images are pulled from private repository
  imagePullSecrets:
  pullPolicy: Always
  repository: quay.io/mongodb
