# Name of the Namespace to use
namespace: mongodb

## Operator

# Set this to true if your cluster is managing SecurityContext for you.
# If running OpenShift (Cloud, Minishift, etc.), set this to true.
managedSecurityContext: false

operator:
  # Execution environment for the operator, dev or prod. Use dev for more verbose logging
  env: prod

  # Name that will be assigned to most of internal Kubernetes objects like Deployment, ServiceAccount, Role etc.
  name: mongodb-enterprise-operator

  # Name of the operator image
  operator_image_name: mongodb-enterprise-operator

  # Name of the deployment of the operator pod
  deployment_name: mongodb-enterprise-operator

  # Version of mongodb-enterprise-operator
  version: 1.14.0

  # The Custom Resources that will be watched by the Operator. Needs to be changed if only some of the CRDs are installed
  watchedResources:
  - mongodb
  - opsmanagers
  - mongodbusers

  # Create operator-service account
  createOperatorServiceAccount: true

## Database
database:
  name: mongodb-enterprise-database
  version: 2.0.2

initDatabase:
  name: mongodb-enterprise-init-database
  version: 1.0.5

## Ops Manager
opsManager:
  name: mongodb-enterprise-ops-manager

initOpsManager:
  name: mongodb-enterprise-init-ops-manager
  version: 1.0.5

## Application Database
initAppDb:
  name: mongodb-enterprise-init-appdb
  version: 1.0.8

agent:
  name: mongodb-agent
  version: 11.0.5.6963-1

mongodb:
  name: mongodb-enterprise-appdb-database
  repo: quay.io/mongodb


## Registry
registry:
  imagePullSecrets:
  # TODO: specify for each image and move there?
  pullPolicy: Always
  # Specify if images are pulled from private registry
  operator: quay.io/mongodb
  database: quay.io/mongodb
  initDatabase: quay.io/mongodb
  initOpsManager: quay.io/mongodb
  opsManager: quay.io/mongodb
  initAppDb: quay.io/mongodb
  appDb: quay.io/mongodb
  agent: quay.io/mongodb

multiCluster:
  clusters: []
  kubeConfigSecretName: mongodb-enterprise-operator-multi-cluster-kubeconfig


# Set this to false to disable subresource utilization
# It might be required on some versions of Openshift
subresourceEnabled: true
